# Render manifest (minimal) for Bomet — backend service only
# Keep this file minimal so Render's Blueprint detection (repo+branch in the UI)
# can apply the manifest without conflicts. Do NOT commit secrets here.

services:
  - type: web
    name: bomet-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: "/healthz"
    envVars:
      - key: MONGODB_URI
        value: "<SET_IN_DASHBOARD>"
      - key: ADMIN_KEY
        value: "<SET_IN_DASHBOARD_OPTIONAL>"

# Notes:
# - When creating the Blueprint in Render pick this repository and branch (main).
# - Set MONGODB_URI and ADMIN_KEY in the Render dashboard (Environment > Environment Variables).
# - If you'd like Render to also host the frontend, I can add a separate static site
#   configuration after you confirm the backend entry is accepted.