# Render manifest (minimal) for Bomet — backend service only
# Keep this file minimal so Render's Blueprint detection (repo+branch in the UI)
# can apply the manifest without conflicts. Do NOT commit secrets here.

services:
  - type: web
    name: bomet-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
  autoDeploy: true
  healthCheckPath: "/healthz"

# Notes:
# - When creating the Blueprint in Render pick this repository and branch (main).
# - IMPORTANT: do NOT add placeholder env vars in this file. Instead, set the following
#   Environment Variables in the Render dashboard (Service > Environment > Environment Variables):
#     - MONGODB_URI = <your mongodb connection string, starts with mongodb:// or mongodb+srv://>
#     - ADMIN_KEY = <optional admin key used to clear leaderboard>
# - If you'd like Render to also host the frontend, I can add a separate static site
#   configuration after you confirm the backend entry is accepted.