# Render manifest for Bomet repository
# This file configures two services:
#  - bomet-backend: a Node web service that runs from the backend/ folder
#  - bomet-frontend: a static site served from the public/ folder
#
# Before using, replace <REPO_URL> with your repository URL in the Render dashboard
# and set environment variables in the Render dashboard (do NOT commit secrets here).

services:
  - type: web
    name: bomet-backend
    env: node
    plan: free
    repo: "<REPO_URL>"
    branch: main
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: "/healthz"
    envVars:
      - key: MONGODB_URI
        value: "<SET_IN_DASHBOARD>"
      - key: ADMIN_KEY
        value: "<SET_IN_DASHBOARD_OPTIONAL>"

static_sites:
  - name: bomet-frontend
    repo: "<REPO_URL>"
    branch: main
    rootDir: "."
    buildCommand: ""
    publishPath: "public"
    autoDeploy: true

# Notes:
# - Replace <REPO_URL> with the HTTPS git URL for your repository.
# - Configure the environment variables in the Render dashboard for security.
# - If you prefer to host the frontend separately (e.g., Vercel), remove the static_sites section.